- name: set fstab
  template: src=fstab
            dest=/etc/fstab
            owner=root
            group=root
            mode=644

- name: ensure /mnt/timecapsule exists
  file: path=/mnt/timecapsule
        state=directory
        owner=root
        group=root
        mode=777

- name: ensure /mnt/media exists
  file: path=/mnt/media
        state=directory
        owner=root
        group=root
        mode=777
