---
- hosts: "{{hostname}}"
  roles:
    - user
    - sudo
    - ssh
    - fstab
    - network
    - ntp
    - netatalk
    - vim
    - btsync
    #- rtorrent
    - java
    - minecraft
  vars_files:
    - vars.yml
  sudo: yes
