---

- name: create standard user
  user: name={{user}}
        password={{password}}
        update_password=on_create
        append=yes
        groups=sudo
        state=present

- name: ensure pi user is gone
  user: name=pi
        remove=yes
        state=absent
