- name: install netatalk
  pacman: name=netatalk
          state=installed
  sudo: yes

- name: configure afp.conf
  template: src=templates/afp.conf
            dest=/etc/afp.conf
			owner=root
			group=root
			mode=644
  sudo: yes
  notify:
    - reload netatalk
  
- name: start and enable netatalk
  service: name=netatalk
           enabled=yes
           state=started
  sudo: yes