#- name: install netatalk build dependencies
  #apt:  pkg={{item}}
        #state=present
  #with_items:
    #- build-essential
    #- libssl-dev
    #- libgcrypt11-dev
    #- libkrb5-dev
    #- libpam0g-dev
    #- libwrap0-dev
    #- libdb-dev
    #- libavahi-client-dev
    #- libacl1-dev
    #- libldap2-dev
    #- libcrack2-dev
    #- systemtap-sdt-dev
    #- libdbus-1-dev
    #- libdbus-glib-1-dev
    #- libglib2.0-dev
    #- tracker
    #- libtracker-sparql-0.14-dev
    #- libtracker-miner-0.14-dev

#- name: copy netatalk
  #unarchive:  src=netatalk-3.1.1.tar.bz2
              #dest=/usr/local/src/

#- name: configure build
  #command:  action=./configure --with-init-style=debian --with-cracklib --enable-krbV-uam --with-pam-confdir=/etc/pam.d --with-dbus-sysconf-dir=/etc/dbus-1/system.d --with-tracker-pkgconfig-version=0.14
            #chdir=/usr/local/src/netatalk-3.1.1/

#- name: make
  #command:  action=make
            #chdir=/usr/local/src/netatalk-3.1.1/

#- name: make install
  #command:  action=make install
            #chdir=/usr/local/src/netatalk-3.1.1/

- name: configure afp.conf
  template: src=afp.conf
            dest=/usr/local/etc/afp.conf
            owner=root
            group=root
            mode=644
  notify:
    - reload netatalk

- name: start and enable netatalk
  service: name=netatalk
           enabled=yes
           state=started
