- name: install openssh
  apt:  pkg=openssh-server
        state=present
  sudo: yes

- name: configure sshd_config
  template: src=sshd_config
            dest=/etc/ssh/sshd_config
            owner=root
            group=root
            mode=644
            backup=yes
  sudo: yes
  notify:
    - reload sshd

- name: start and enable ssh
  service: name=ssh
           enabled=yes
           state=started
  sudo: yes
